### PR TITLE
Add a note about local-deployer's usage scope

### PR DESCRIPTION
**Pull request by sabbyanandan**

### CODE REVIEW

**Comment by ericbottard** [comment]
After second thought, I think this comment belongs in the SCDF core reference manual.
Users are unlikely to get discouraged from using local in production because they read about it here (a building block)

**Comment by sabbyanandan** [comment]
We could add it in both the places.

**Comment by ericbottard** [comment]
Merging this one with formatting changes, please open another PR as you see fit

**Comment by ericbottard** [comment]
Merged as 90f5409b3edba750405a29a55194748b577126e7

**Pull request closed without merging**
