### PR TITLE
Docker command builder should support custom container names

### PR DESCRIPTION
**Pull request by hekonsek**
Hi,

What do you think about providing some control over the name assigned to created Docker containers? In particular I'd highly appreciate an ability to provide a property which will indicate the name of the created container.

For example for property `docker.container.name=myapp` and `spring.cloud.deployer.count=3`, I'd like to have three containers created with the following names:
```
myapp-0
myapp-1
myapp-2
```

Such addition will be extremely useful for development and test environments, as many existing dev/QA tools and scripts make some assumptions about the containers names.

Cheers!

### CODE REVIEW

**Comment by ericbottard** [comment]
Overall, the idea looks good to me, with the exception that `DOCKER_CONTAINER_NAME_KEY` should typically be a **deployment properpty** (ie coming from the `spring.cloud.deployer.xxx` namespace) rather than from `args`. Indeed, it is something that instructs the (specific) deployer how to behave

**Comment by hekonsek** [comment]
Good point, Eric. Added the proper prefix.

**Comment by ericbottard** [comment]
Actually, it's not just a name change. You'll need to change *where* you get the property from.

The aim is that users would ultimately use it like so:
```
stream deploy bo --properties "deployer.log.docker.container.name=gogo"
```

**Comment by hekonsek** [comment]
Ah, sorry - I confused deployment properties with application args. Mea culpa. :) Submitted fix.

**Comment by hekonsek** [comment]
Right now I can specify container name like:

```
Map<String,String> deployProps = new HashMap<>();
deployProps.put("spring.cloud.deployer.docker.container.name", "myName");
Map<String,String> props = new HashMap<>();
deployer.deploy(new AppDeploymentRequest(new AppDefinition("myApp", props), new DockerResource("myContainer"), deployProps));
```

Is that the same result you have in mind?

**Comment by ericbottard** [comment]
Yes, although obviously this would not be done programmatically in the context of Data Flow, but through the `--properties "deployer.foo.docker.container.name=myName"` shell argument.

Your last commit seems legit (haven't tested though).

Thanks again for the contribution!

**Comment by hekonsek** [comment]
Many thanks for a review, Eric. Let me know if I can do anything else to help with this PR.

**Comment by ericbottard** [comment]
Merged as e47ebfb with added test and updated `@author` tags

**Comment by hekonsek** [comment]
Many thanks, Eric!

**Pull request closed without merging**
