### PR TITLE
Add profile to deployer configuration

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- This will let us enable/disable specific deployer based on profile

### CODE REVIEW

**Comment by jvalkeal** [comment]
Using a profile with autoconfiguration, IMHO, creates more problems than what it's trying to resolve. I'd go with `enable` property. Other than that I don't think a framework lib should use any profiles anyway.

**Comment by ilayaperumalg** [comment]
@jvalkeal ok, by `enable` property do you mean something like `spring.cloud.deployer.local.enable`?

**Comment by jvalkeal** [comment]
yeah, something like that. Think it's a bigger topic to discuss generally how to enable/disable deployers if more that one are in a CP.

**Comment by ilayaperumalg** [comment]
Closing this based on the discussion above. This requires some re-work.

**Pull request closed without merging**
